### ISSUE TITLE
whatsapp tally-pdf attachment issue

### ISSUE THREAD

**Issue by kamillakhani** [tejavarma-aln/TallyWhatsappSender#10]
after opening the WhatsApp web window the invoice pdf is not attaching. Its empty. please help me out. chrome is not attaching the invoice in WhatsApp.

**Comment by kamillakhani** [comment]
![Uploading 118167346...]

**Comment by kamillakhani** [comment]
![image](https://user-images.githubusercontent.com/84141847/118167442-fc533300-b426-11eb-9819-a49ea1619288.jpeg)

**Comment by sohanpatidar27** [comment]
same here

**Comment by sohanpatidar27** [comment]
after opening the WhatsApp web window the invoice pdf is not attaching. Its empty. please help me out. chrome is not attaching the invoice in WhatsApp.

**Comment by tejavarma-aln** [comment]
DLL updated:
Replace TallyWhatsappsender.dll from here : https://github.com/tejavarma-aln/TallyWhatsappSender/tree/master/Binary
No need to replace all the files

**Comment by kamillakhani** [comment]
Again I need to register the dll
