### ISSUE TITLE
Time issue sir

### ISSUE THREAD

**Issue by kamillakhani** [tejavarma-aln/TallyWhatsappSender#11]
how to change the 60 seconds time to 120 or more. in the 60 seconds the file is attaching but not sending.please help sir

**Comment by tejavarma-aln** [comment]
Change it in the TDL file.
In the system formula, there is an option called waitime.

**Comment by tejavarma-aln** [comment]
Assuming, your query is resolved.

**Comment by kamillakhani** [comment]
I Will try and see. Thank you
