### ISSUE TITLE
Issue in com interface

### ISSUE THREAD

**Issue by Ganeshtdl** [tejavarma-aln/TallyWhatsappSender#12]
![whatsapperror](https://user-images.githubusercontent.com/85726295/121637500-14aa8200-caa7-11eb-83c7-ef3e01469e9f.PNG)

Got error msg like this when i used this codes for whatsapp in tally

**Comment by tejavarma-aln** [comment]
Use that latest TDL
https://github.com/tejavarma-aln/TallyWhatsappSender/tree/master/TDL

**Comment by tejavarma-aln** [comment]
re-solved
