### ISSUE TITLE
Failed to create an object of class of COM Interface! 

### ISSUE THREAD

**Issue by yashmrv** [tejavarma-aln/TallyWhatsappSender#13]
![error](https://user-images.githubusercontent.com/66547827/122218205-d4466c00-cecb-11eb-8604-09c7576eefa0.png)

**Comment by sameerbatavia** [comment]
same issue it was working fine but i uninstalled it now after installation same error


EDIT 
WORKING NOW

**Comment by tejavarma-aln** [comment]
resolved
