### ISSUE TITLE
does not trigger 

### ISSUE THREAD

**Issue by sameerbatavia** [tejavarma-aln/TallyWhatsappSender#2]
regasm TallyWhatsappsender.dll /codebase ;;Give Full path of the TallyWhatsappsender.dll file

 while doing this when my tally is in c:\program files\tally\tally.erp9 folder regasm  doesnt work so i put the dll file in c drive to register the dll

but now after installing tally doesnt trigger the whatsapp ( chrome doesnt open) also where do we put the mobile number?

**Comment by tejavarma-aln** [comment]
1)  Path to the DLL file should be in double quotes
2) Ledger Mobile number will be the Whatsapp number

**Comment by sameerbatavia** [comment]
hi thanks for the quick reply registered dll
loaded tally tdl
while sales entry it exported pdf to a new directory called exported pdf but it did not send the WhatsApp

**Comment by sameerbatavia** [comment]
EDIT

Working FLAWLESSLY

thanks

**Comment by tejavarma-aln** [comment]
Keep going
