### ISSUE TITLE
chrome issue

### ISSUE THREAD

**Issue by sameerbatavia** [tejavarma-aln/TallyWhatsappSender#3]
after every WhatsApp i need to scan WhatsApp again to login in and send another invoice also can you please do this for other reports like ledger etc

**Comment by tejavarma-aln** [comment]
That is the limitation...
In order to do that we have to persist the chrome session, so we can reuse it every time
I will try to do it, your contribution will be welcomed
for ledger and other reports, you can modify the TDL code as per your requirement

**Comment by sameerbatavia** [comment]
hello were you able to sort persistence chrome

**Comment by tejavarma-aln** [comment]
that's great!
