### ISSUE TITLE
Error in TallyWhatsappSender

### ISSUE THREAD

**Issue by sudhir233** [tejavarma-aln/TallyWhatsappSender#7]
Hi Teja Sir,
I am Sudhir Verma, You are rocking in coding.I follow you, sir i am using your whatsapp sender code but there is an error occurring when i send invoice pdf format to customer whatsapp no. And the error is "index was out of range. must be non negative and less than the size of the collection. Parameter name: index". Plz tell me how to resolve this error. i have done all steps which you write in "README.md" file.

**Comment by tejavarma-aln** [comment]
Did you update to the new one?
Use this one: 
https://github.com/tejavarma-aln/TallyWhatsappSender/tree/master/Binary
Replace your old files with new ones in the above link.
