### ISSUE TITLE
persistent chrome

### ISSUE THREAD

**Issue by sameerbatavia** [tejavarma-aln/TallyWhatsappSender#8]
sir were you able to get persistence chrome so we dont have to open again and again

**Comment by tejavarma-aln** [comment]
you mean, you have done that?

**Comment by kunalkhandol** [comment]
Hello
I tried to load this TDL in TallyPrime
I registered DLL and showing this below message

RegAsm: warning RA0000: Registering an unsigned assembly with /codebase can cause your assembly to interfere with other applications that may be installed on the same computer. The /codebase switch is intended to be used only with signed assemblies. Please give your assembly a strong name and re-register it.
Types registered successfully

and after that, I loaded TDL in TallyPrime, while doing a Sale entry and press (Y) when asking Send WhatsApp?

but it shows error message like COM Interface is not invokable or DLL is not registered

TDL File Path:
<Drive>:/TallyPrime/TallyWhatsappsender/*.exe, *.dll, *.txt files are available

Please assist me where I am wrong.

Thanks in Advance

**Comment by tejavarma-aln** [comment]
Is your system 32 bit or 64 bit?
Are you registering as admin (Open cmd in admin mode)?
Share screenshot  of DLL registration window (Command prompt)

**Comment by kunalkhandol** [comment]
Hello
Thank you for your quick reply

1) I am using 64Bit System

2) Yes I opened Command Prompt in Run as Administrator

3) Please check below image/attachment of the command prompt window

Thanks 


    On Saturday, 27 February, 2021, 03:19:23 pm IST, teja varma <notifications@github.com> wrote:  
 
 


Is your system 32 bit or 64 bit?
Are you registering as admin (Open cmd in admin mode)?
Share screenshot of DLL registration window (Command prompt)

**Comment by tejavarma-aln** [comment]
Did find any attachment?

**Comment by kunalkhandol** [comment]
HelloSorry for that,please find the attachment below.
    On Saturday, 27 February, 2021, 05:40:50 pm IST, teja varma <notifications@github.com> wrote:  
 
 


Did find any attachment?

**Comment by tejavarma-aln** [comment]
I didn't get any attachments?
upload it somewhere and share the link.

**Comment by sameerbatavia** [comment]
> you mean, you have done that?

no sir was asking if you found out the solution

**Comment by tejavarma-aln** [comment]
> > you mean, you have done that?
> 
> no sir was asking if you found out the solution

Not yet.
I currently indulge in other projects, soon will update this one

**Comment by kunalkhandol** [comment]
Hello,Sorry 
can you please check this link for the command prompt screenshothttps://ibb.co/RS9wjCs

let me know if you need anything else

Thanks again    On Monday, 1 March, 2021, 01:56:24 pm IST, teja varma <notifications@github.com> wrote:  
 
 




you mean, you have done that?


no sir was asking if you found out the solution


Not yet.
I currently indulge in other projects, soon will update this one

**Comment by tejavarma-aln** [comment]
Everything is fine as per your image.
