### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tamjeet** [tejavarma-aln/TallyWhatsappSender#9]
Unable to send file.
 
open whatsapp web and also attached file work fine but after attaching file, whatsapp web get closed automaticaly without sending   file.

calculator shows below error. pls do the  needful
[ERROR.xlsx](https://github.com/tejavarma-aln/TallyWhatsappSender/files/6106241/ERROR.xlsx)

**Comment by tejavarma-aln** [comment]
DLL updated:
Replace TallyWhatsappsender.dll from here : https://github.com/tejavarma-aln/TallyWhatsappSender/tree/master/Binary
No need to replace all the files
